security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Security\StaticUser: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        static_users:
            id: App\Security\StaticUserProvider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt)/
            security: false
        main:
            lazy: true
            provider: static_users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_user
            logout:
                path: app_logout
                target: app_user

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/carriere/company/new, roles: ROLE_COMPANY }
        - { path: ^/carriere/company/\d+/edit, roles: ROLE_COMPANY }
        - { path: ^/carriere/opportunity/new, roles: ROLE_COMPANY }
        - { path: ^/carriere/opportunity/\d+/edit, roles: ROLE_COMPANY }
        - { path: ^/carriere/apply, roles: ROLE_USER }
        - { path: ^/carriere/my-applications, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon


